### ISSUE TITLE
Bug: Cursor with ascending sort fails

### ISSUE THREAD

**Issue by latotty** [webiny/commodo#16]
This test should work:

https://github.com/latotty/commodo/commit/1da09ccb0e08ec7e4a39d26700811fd0a24da5b3

Am I doing something wrong, or is it something wrong with the commodo?

**Comment by Pavel910** [comment]
@latotty fixed in https://github.com/webiny/commodo/commit/d7b8ec90ff5dacfd3e6852e873a6688f60c0bb3c.

Will be released later today :)
